print("================================")
print(" INDENTATION ERROR LAB")
print("================================")
print("IndentationError happens when:")
print("1. Missing spaces inside if/for/while")
print("2. Mixing tabs and spaces")
print("3. Wrong number of spaces")
print("================================")
print("EXAMPLE FIX:")
print("WRONG:")
print("if x == 1:")
print("print(hello)")
print("RIGHT:")
print("if x == 1:")
print("    print(hello)")
print("================================")
print("RULE: Always use 4 spaces!")
