print("================================")
print(" NAME ERROR LAB")
print("================================")
print("NameError happens when:")
print("1. Variable not defined yet")
print("2. Typo in variable name")
print("3. Using variable before assigning it")
print("================================")
print("EXAMPLE FIX:")
print("WRONG: print(username)")
print("RIGHT: username = DevOOk")
print("       print(username)")
print("================================")
print("RULE: Always define variable first!")
print("================================")
username = "Dev00k"
print("Example:", username)
