print("================================")
print(" SYNTAX ERROR LAB")
print("================================")
print("Common SyntaxErrors:")
print("1. Missing closing bracket )")
print("2. Missing quotes")
print("3. Missing colon after if/for/while")
print("================================")
print("EXAMPLE FIX:")
print("WRONG: if x == 1")
print("RIGHT: if x == 1:")
print("================================")
