print("================================")
print(" TYPE ERROR LAB")
print("================================")
print("TypeError happens when:")
print("1. Mixing text and numbers")
print("2. Wrong type of data")
print("3. Wrong number of arguments")
print("================================")
print("EXAMPLE FIX:")
print("WRONG: print(22 + hello)")
print("RIGHT: print(str(22) + hello)")
print("================================")
print("RULE: Match your data types!")
print("================================")
port = 22
message = "Port number is: " + str(port)
print(message)
